### ISSUE TITLE
Mosparo Custom Integration: Stylesheet not loading

### ISSUE THREAD

**Issue by OriCat101** [mosparo/mosparo#113]
I’m trying to integrate Mosparo onto my webpage and I’m running into an issue with the custom integration.

I’m linking the stylesheet as described in the [Mosparo documentation](https://documentation.mosparo.io/docs/integration/custom#embed-css-resources):

`<link href="#local.mosparoConfig.host#/resources/#local.mosparoConfig.uuid#.css" rel="stylesheet" />
`
However, my custom designs won’t load and only the default design is displayed. While debugging, I noticed that the URL of the stylesheet redirects me when opened in the browser:

`<link href="#local.mosparoConfig.host#/resources/#local.mosparoConfig.uuid#/b9edfc8717218c1772c734cd39918c0ac138c0e4f462b72e66c1fd11f81bfe89.css" rel="stylesheet" />`
If I enter this URL directly into the link tag, then the stylesheet loads without any issues.

My main question is: what is the part that comes after the UUID and where do I get it from? I can’t just enter it statically because I have to generate the URL dynamically (that’s why there are variables in the <link> tag).

Regards, Ori

**Comment by zepich** [comment]
Hi Ori

Thank you very much for your question.

**To answer the main question:**
The last part of the stylesheet URL is the hash of your design settings. As soon as you change the design settings, the hash will be regenerated, forcing the browser to load the stylesheet file again (for cache busting - that's at least the idea).

There are two options to get the correct URL:

1. You can use the redirection. In general, if you call the URL (like you described) `<link href="#local.mosparoConfig.host#/resources/#local.mosparoConfig.uuid#.css" rel="stylesheet" />` it should redirect the request to the correct URL with the hash included.
2. There is a small (probably not documented) API that gives you this full URL. You can send a standard GET request to the following URL: `#local.mosparoConfig.host#/resources/#local.mosparoConfig.uuid#/url`. The response is the complete URL to the latest stylesheet URL with the hash as text. We use this method to cache the full URL in the WordPress plugin.

**Now to your main problem:**
You wrote that you see the default styles. This generally happens if the stylesheet cache for a project is unavailable. Since you see the stylesheet when you include the full URL, my best explanation is the Browser Cache. Have you tried it in a new browser or a private browser once?

If you have the same issue in a private or fresh browser, can you check the content of the file `/public/resources/mappings.php`? There you should see the UUID of the project as well as the hash of the design settings. Is this hash the same as when you open the URL in the browser directly?

Kind regards,

zepich

**Comment by OriCat101** [comment]
Hi,

Thank you for your quick response. I checked and the hashes were the same, and I also had the browser cache disabled for the entire time. However, the issue seems to have resolved itself today after I rebooted the entire system.

Is it possible that the stylesheet was cached somewhere along the way, for example in Docker (I’m not sure if Docker does that) or on the Mospare server?

Let me know if you have any thoughts on this. Thanks!
