### ISSUE TITLE
Testrule applies to all projects

### ISSUE THREAD

**Issue by MaPhiKo** [mosparo/mosparo#160]
I have 3 projects in my Mosparo installation.
One of them has no rules set yet while the other two have rules blocking a test email adress. 
Entering the test email adress in the form linked to the project with no rules gets a spam response and in the submission the rating for both rules is counted.

**Comment by zepich** [comment]
Hi @MaPhiKo 

Thank you very much for this very interesting issue. It took a while to figure out the possible problem for this issue.

I think in your installation, an exception occurs in the cleanup logic - at least this way, I can reproduce the issue you described.

In the cleanup logic, we have to disable the project filter. Because of the exception in the cleanup logic, the filter stays disabled, and the normal validation logic continues - but without a project filter. Because of this, all possible rules will be loaded from the database instead of just the ones from the active project.

We've just released v1.0.6, which addresses this issue. If you update, you should no longer have this problem.

Additionally, I've added a logging functionality to log the reason for the exception. After some form submissions, can you check the log file to see the original error? The file is stored in `var/log/prod-{date}.log`. Can you have a look and create a new issue with the visible error so we can fix that as well?

Thank you very much for your excellent finding and help making mosparo better!

Kind regards

zepich

**Comment by zepich** [comment]
@MaPhiKo Can you recheck the log? Are there any other error messages besides the one you reported in issue #161?

Because the origin of this issue here should also be a problem that still needs to be fixed (since I don't know what the real issue was for this one)...

**Comment by MaPhiKo** [comment]
@zepich There is a new error that repeats continuously. It seems to have started when I applied the most recent update to mosparo. I replaced the database name.
[2023-11-28T20:42:55.795835+01:00] app.CRITICAL: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`*databaseName*`.`submit_token`, CONSTRAINT `FK_6C047AC88DF22AA4` FOREIGN KEY (`last_submission_id`) REFERENCES `submission` (`id`)) [] []
