### ISSUE TITLE
Why doesn't Mosparo flag duplicates as SPAM?

### ISSUE THREAD

**Issue by Geremia** [mosparo/mosparo#168]
If I submit exactly the same form entries multiple times, why doesn't Mosparo flag the subsequent duplicates as SPAM?

**Comment by zepich** [comment]
Hi @Geremia 

Did you enable the minimum time security feature? If yes, that would explain it since the first request was too fast, but the second one was not.

Tell me more about what catches the submission if you haven't enabled that feature. You should see why the first one got caught in the submission details. Is it because of a rule?

Thank you very much for your information.

Kind regards,

zepich

**Comment by Geremia** [comment]
@zepich I mean that Mosparo currently can set "Is spam" to "No" for multiple identical (same `formSignature`) submissions with the same form data.

**Comment by zepich** [comment]
Hi @Geremia 

I'm sorry, I misunderstood you.

mosparo does not have such functionality right now simply because we didn't have this idea.

Thank you very much for your excellent idea! I will add it to the list of future developments in the [Discussions](https://github.com/mosparo/mosparo/discussions).

Kind regards,

zepich

**Comment by zepich** [comment]
See #170

**Comment by zepich** [comment]
Hi @Geremia 

Happy New Year!

Can we close this issue for now?

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @Geremia 

With the newly released version 1.2, mosparo can now block repetitive submissions.

Please let me know if you need any help.

Kind regards,

zepich
