### ISSUE TITLE
[Question] PostgreSQL

### ISSUE THREAD

**Issue by skid9000** [mosparo/mosparo#178]
Hello,

i saw from your .env files that you use `Doctrine` ORM for DB management but specify "MySQL or MariaDB" as a requirement in your documentation.

As Doctrine support PostgreSQL, i was wondering what that requirement really means for you.

Are you using specific instruct sets that only works on MySQL which cannot be translated to PostgreSQL?
Or is it that mosparo is only tested for MySQL as it is (i suppose) the dbms you're most used to but it "could" work with PostgreSQL?

If it's the second guess, could you consider adding PostgreSQL as a supported DBMS for mosparo in your documentation?

**Comment by zepich** [comment]
Hi @skid9000 

Thank you very much for your question.

Doctrine, Symfony, and (I guess) mosparo should work perfectly with PostgreSQL. From my perspective, we do nothing special with the database, so there should be no problem with the queries and the schema (I think).

We investigated that issue before starting with the private beta and had some general troubles. I think - but I cannot remember - we had problems with the Doctrine Migrations Bundle, which we use for the database schema.

I just googled and tried to find out the problem again, but I cannot find anything. It could be a different problem (not Doctrine Migrations Bundle), or we didn't try it too much back then.

I will have another look at it and try to find out the reason why we didn't do it (or try to find the solution for this).

Thank you very much for bringing this to our attention!

Kind regards

zepich

**Comment by zepich** [comment]
Hi @skid9000 

I've tested it with the latest mosparo version and found the problem.

The migrations with the Doctrine Migrations Bundle are a problem, but that should be a solvable problem. The reason is that these are plain SQL queries that are incompatible between MySQL and PostgreSQL.

The other, more significant issue is the comments on the column for some special Doctrine column types that we use (in our type and the types from the [Doctrine Encryption Bundle by Gracious](https://github.com/graciousagency/doctrine-encryption-bundle)). These define the `COMMENT` for a column directly in the SQL statement, and therefore, it's impossible to create any SQL queries to create the tables for PostgreSQL. It's also a solvable problem. I tried that in a test environment, and it will work, but it needs some work.

We will put that on our TODO list and make mosparo support PostgreSQL databases. The number one priority for us is to support as many different setups as possible.

The negative part is that this will take some time and will not be available for the next weeks. In the best case, we can add it in v1.2, which is planned for the next months (release around April/May).

Kind regards,

zepich

**Comment by skid9000** [comment]
That's great to hear! Thank you for looking into this!

**Comment by zepich** [comment]
I'm closing this issue because I created a new development issue with the to-dos for this enhancement. See #185

**Comment by zepich** [comment]
Hi @skid9000 

As you may seen, we've released version 1.2 today with the official support for PostgreSQL.

Please let me know if you need any help.

Kind regards,

zepich
