### ISSUE TITLE
mosparo shows cloudflare ip not the origin ip

### ISSUE THREAD

**Issue by Ratingthomas** [mosparo/mosparo#20]
When a user submits a form I see the Cloudflare servers ip not the ip of the users pc. 
<img width="162" alt="Schermafbeelding 2023-03-15 om 12 40 09" src="https://user-images.githubusercontent.com/92450283/225298557-8098b8fb-9f8e-4cbb-9f6b-7de501a13106.png">

**Comment by zepich** [comment]
@Ratingthomas Thank you very much for the issue!

**Comment by zepich** [comment]
@Ratingthomas, I've added a workaround for this issue.

Can you please update to v0.3.8? 

1. After the update, there is a file called `.env.local.dist` in the root directory of mosparo.
2. Please copy (or rename) this file to `.env.local` (with the dot at the beginning).
3. Edit the file `.env.local` and uncomment the correct line. For your case (CloudFlare), uncomment line 13 (the line **after** the text with `# If you use CloudFlare...`)
4. Submit a form and check the IP address in mosparo

We will add a better solution with the next major version (v0.4), where this setting (and settings for other providers than CloudFlare) are manageable in the administration interface instead of changing environment files.

I'm looking forward to your feedback.

**Comment by Ratingthomas** [comment]
Thank you very much, now I see the right ip address!
