### ISSUE TITLE
Specified hosts at Project-Settings->Main Settings are ignored

### ISSUE THREAD

**Issue by zttom** [mosparo/mosparo#217]
Hosts are ignored when specifying hosts at main settings. 

We have specified test.de as host and are using the frontend at foo.de. The verification is still valid. 

We would assume that Mosparo should block all verification requests from not listed hosts (request-submit-token and check-form-data).

**Comment by zepich** [comment]
Hi @zttom 

Thank you very much for reporting this issue.

I will look into this issue.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @zttom 

Thank you very much for your report.

I've looked into the issue and can confirm that these hosts are not doing anything right now.

The idea of these hosts is to respond with the correct CORS headers for the defined hosts and not return a proper CORS header for all other hosts. 

However, these hosts are only used for the CORS headers and not to protect the API from access from an unwanted host since there is no technical feature to block such requests. When the `Origin` header is not set in the request, or the value is `null`, we cannot know where a request is coming from. 

For example, suppose you fake the form submission by manually making HTTP requests with a backend language (like PHP or Python). In that case, you can 'simulate' the whole process, and we will not have an `Origin` header to protect the API from it. If we require the `Origin` header in the request since it should always be set for CORS requests, you can also fake the `Origin` header in a faked PHP or Python HTTP request to the API.

We will adjust the host settings. We add the correct functionality for the CORS headers to respect the defined hosts. We will add an additional wildcard syntax (for example, `*.example.com`) and a better help text to describe the option correctly.

These changes will be released with the next minor version, v1.2. In theory, it's a bug, and the change is not that big — but it can be a breaking change for a project where the hosts are not defined correctly right now. By releasing it with the next minor version, we can inform the users about this possible breaking change.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @zttom 

With the release of v1.2 today, this issue is officially fixed, and the hosts are no longer ignored.

Thank you very much for reporting this issue!

Kind regards,

zepich
