### ISSUE TITLE
mosparo honeypot field is incorrectly located and is visible.

### ISSUE THREAD

**Issue by Sapper-Morton** [mosparo/mosparo#223]
Hi!

More issues from me :)

The Mosparo honeypot field gets inline style: position: absolute !important; left: -1000px !important; top: -1000px !important;
This causes the field be visible if the form is located in bottom right of the site.

For now I have to hide it using CSS:
input[name="given_honeypot_field_name"] {
display:none!important;
}

![image](https://github.com/mosparo/wordpress-plugin/assets/23439320/d1012450-0c9b-4d81-8632-ca86c8a188cc)

p.s. Thank you for so much help thus far!

**Comment by zepich** [comment]
Hi @Sapper-Morton 

Thank you very much for your report.

Since this is an issue with mosparo itself and not the WordPress plugin, I've moved the issue to the mosparo repository and renamed it.

I will look into this issue and add a fix. A new version with the fix should be released over the weekend.

> p.s. Thank you for so much help thus far!

You're welcome! Thank you very much for your testing and reporting.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @Sapper-Morton 

With the released version v1.1.5, the honeypot field now has better styles and should not be visible anymore.

Thank you, @nmcodeeu, for providing the base for the fix.

Kind regards,

zepich
