### ISSUE TITLE
Verification bug

### ISSUE THREAD

**Issue by mohamadng** [mosparo/mosparo#225]
Hi
There is a problem at verification process.
data to verify is:
{"username":"09356488086","ms_uuid":"87ba7e9d-f55b-4e69-b88a-22055c6cc292","ms_key":"915eccbdda3480bbc6c7e43188d48f3a","inp_ms_key":"915eccbdda3480bbc6c7e43188d48f3a","eesalt":null,"step":"start","_mosparo_submitToken":"PjLB61OKp28kR4u9wSrxPEBgcMo9WA0NGZNe3lsiW0g","_mosparo_validationToken":"DanSlExHgsJ-jwev0aljmSEqIXIYeYv-8uIRL6gD-MY"}

As you see there are both submit and validate token in data but result is:

{"isSubmittable":false,"isValid":false,"getVerifiedFields":[],"getIssues":[{"message":"Submit token not found or not valid."}]}

This happens about  10 percent of all requests and both tokens are exists in mosparo database.

 Thank you for so much help thus far!

**Comment by zepich** [comment]
Hi @mohamadng 

Thank you very much for your issue.

This error message can have two reasons (https://github.com/mosparo/mosparo/blob/master/src/Controller/Api/V1/Verification/VerificationApiController.php#L89):

1. The submit token is not in the database (anymore)
2. A submission for this submit token was already verified

Since you wrote that you found the submit token in the database, I guess the problem is that it's already verified. To confirm that, can you maybe enable the API debug mode in the project settings and try to get this error again? You should have more information in the response.

Is it possible that the same submit token was already used? Do you have some cache on your website or something like that? Or do you submit the form by XHR/AJAX, and is it possible to submit it twice?

Kind regards,

zepich

**Comment by mohamadng** [comment]
Hi @zepich 
Thank you for so much help.
I almost read all mosparo backend codes, and been used debug mode. Problem in none of them.
project use ajax but there is no way that user can submit the form twice. we use these code to reduce fails and it really worked:

`if (!$this->Recaptcha->validate($d)){
                            if (!empty($this->getRequest()->getData('_mosparo_submitToken')) && !empty($this->getRequest()->getData('_mosparo_validationToken'))){
                                sleep(1);
                                if (!$this->Recaptcha->validate($d)){
                                    ...
                                    return $this->setJsonResponse([
                                        'message' => 'there is problem',
                                        'result' => $result,
                                        'errors' => $result['errors']
                                    ], 400);
                                }`

Please consider these:
1) in most cases retry (with same token) solve the problem (means submit token was NOT already verified)

2) Some times this command `bin/console mosparo:cleanup-database` fire a database exception due to foreign key problem the main function of this command used at https://github.com/mosparo/mosparo/blob/25de7559be56a78f0387504bac6df0b54248c337/src/Controller/Api/V1/Frontend/FrontendApiController.php#L94

Thank you for so much help thus far!

**Comment by zepich** [comment]
Hi @mohamadng 

Thank you very much for your update.

Okay, very interesting. So, if you can add a `sleep(1);` or try again after a second (as you wrote), it means that the submit token is not in the database when mosparo tries to query it in the verification API.

In that case, I think it has to do with the database setup. Do you have a database setup with replication (like one source database server and one or multiple replicas)? Or do you have a (special) database cache in front of your database server?

Regarding the cleanup exceptions, I think the two problems are connected. So, if we can understand the first one, I guess we also understand the other one.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @mohamadng 

Did you find a reason for this issue, or were you able to solve it?

Thank you very much for your feedback.

Kind regards,

zepich

**Comment by zepich** [comment]
Closed because of inactivity.
