### ISSUE TITLE
Submissions pane blank, but submisions showing in Dashboard graph

### ISSUE THREAD

**Issue by Geremia** [mosparo/mosparo#237]
My Submissions pane is blank:
![Submissions](https://github.com/mosparo/mosparo/assets/4298614/1878cac7-0b17-4095-84f4-d68ab452605a)

But submissions appear in the Dashboard graph:
![Dashboard](https://github.com/mosparo/mosparo/assets/4298614/9e85f3bb-4f0f-415e-ab61-5585307f052a)

I regularly run
```
console mosparo:cleanup-database
console mosparo:rulesets:refresh
console mosparo:geoip2:download-database
```
in my crontab, too.

**Comment by zepich** [comment]
Hi @Geremia 

Thank you very much for your issue!

Since the table is loaded with an XHR/AJAX request, this problem means that the request was not successful (error 500).

Can you look in the mosparo log file (`var/log/prod-{date}.log` in the mosparo directory) or the web server log file if you see any errors?

Kind regards,

zepich

**Comment by Geremia** [comment]
@zepich 
> Since the table is loaded with an XHR/AJAX request, this problem means that the request was not successful (error 500).

I didn't get any 500 error.



> Can you look in the mosparo log file (`var/log/prod-{date}.log` in the mosparo directory)

```
[2024-06-03T21:58:29.306938+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\EntityNotFoundException: "Entity of type 'Mosparo\Entity\SubmitToken' for IDs id(469) was not found" at EntityNotFoundException.php line 31 {"exception":"[object] (Doctrine\\ORM\\EntityNotFoundException(code: 0): Entity of type 'Mosparo\\Entity\\SubmitToken' for IDs id(469) was not found at /var/www/htdocs/mosparo/vendor/doctrine/orm/src/EntityNotFoundException.php:31)"} []
```

**Comment by zepich** [comment]
Hi @Geremia 

Okay, thank you very much for your feedback! I'm happy that it's working again as expected.

I closed this one since you assumed you may have accidentally deleted something in the database.

Please let me know if you need any other help.

Kind regards,

zepich

**Comment by Geremia** [comment]
@zepich  Shouldn't there be a check for database integrity in `console mosparo:cleanup-database` in case of database corruption?

**Comment by zepich** [comment]
Hi @Geremia 

Hmm, interesting question. Did you manually delete something in the database, or did you use the cleanup command when it stopped working?

Technically, the cleanup command should delete the data in the correct order and 'safe', so that if an error happens, the system does not 'break'. Technically, it should also not be possible to create such a situation because of the foreign key, which should prevent deleting one of the rows but not the linked one (between `submit_token` and `submission`).

Can you give me more insight into what you meant with 

"(I think I accidentally deleted something in the database.)"

in the message above? Did you do something manually, or can you recall exactly what you did?

Kind regards,

zepich

**Comment by Geremia** [comment]
> Did you manually delete something in the database

I manually deleted some submissions in the database (using PHPMyAdmin).

**Comment by zepich** [comment]
Hi @Geremia 

Okay, perfect. Thank you very much for the information.

I will reopen the issue and will have a look what we can do in the cleanup logic to resolve such a situation automatically.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @Geremia 

The new version, 1.2.3, contains logic to clean up problematic submissions in case the submit token gets deleted (as in your case).

Additionally, I found another bug with the cleanup logic in a different situation, which I fixed.

I will now close this issue. 

Thank you very much for your help and ideas!

Kind regards,

zepich
