### ISSUE TITLE
Replacement for ReCaptcha?

### ISSUE THREAD

**Issue by quadcom** [mosparo/mosparo#25]
First up, thank you so much for the work that you've put into this project!

Now the question;

Is there a way to configure the operation to work like ReCaptchaV3?

My website form is set up (using Mautic* as the back-end) with ReCaptcha in 'silent mode'? There's no checkbox or button to click or puzzle to complete. For the form submitter, the experience is invisible.

*Mautic! Another open-source project!

**Comment by zepich** [comment]
Hi @quadcom

Thank you very much for your feedback and your question!

There are two answers to your question:

1. Currently, it is impossible to use mosparo as a hidden spam protection method (like, for example, reCAPTCHA V3). This is because we want to give the user the ability to understand what is happening. Of course, most of the users will click the checkbox without thinking. But some of the available CAPTCHA methods use some `magic` to check your data for spam, and we don't like that. We wanted to show visibly what happens and why.

But

2. Technically, there is no reason from our side why it should not be possible (at least in my mind, I haven't tested it). It is impossible with the official mosparo code, but technically, you could copy the mosparo frontend JavaScript and adjust it to your needs. Compared to the current code, the form validation should be done when the user clicks the submit button in your form. Then the user has to wait until mosparo validates the data, and if the validation is completed successfully, the form can be submitted directly. That should be possible and would do it exactly like other hidden spam protection methods.

I will add your suggestion to our list of ideas for future development (the list is not publicly available right now, but it will be soon).

**Comment by zepich** [comment]
Hi @quadcom 

As promised, I've added the list of our ideas and suggestions as posts in the discussion section in this repository: [Discussions](https://github.com/orgs/mosparo/discussions)

You can upvote ideas and suggest additional ideas.

I've added the idea for invisible protection there as well: #53 

If you have any questions, please let me know.

Kind regards,

zepich
