### ISSUE TITLE
False positive for field verification

### ISSUE THREAD

**Issue by fbentele** [mosparo/mosparo#272]
Hi there, 
i just started using mosparo on some projects, and after a few days i wanted to check if it works correctly. now i saw some valid form submissions and i cloudn't figure out what the validation error is. maybe you can guide me in the right direction?

I have a pretty basic mosparo setup with all-default settings. I use it in a wordpress environment but implemented the verification myself (due to custom plugin logic). The verification is somewhat:
```
function kdgs_is_no_spam() {
	Utils::chooseHandler();

	$client = new Mosparo\ApiClient\Client( 
            KDGS_SPAM_PROTECTION_URL, 
            KDGS_SPAM_PROTECTION_PUBLIC_KEY, 
            KDGS_SPAM_PROTECTION_PRIVATE_KEY
        );

	$mosparo_submit_token     = $_POST['_mosparo_submitToken'] ?? '';
	$mosparo_validation_token = $_POST['_mosparo_validationToken'] ?? '';

	$result = $client->verifySubmission( $_POST, $mosparo_submit_token, $mosparo_validation_token );

	return $result->isSubmittable();
}
```

This works for my test submissions and most of "real-world" submissions. But on some submissions (in french, maybe some accents?) i receive a validation error:

![Screenshot 2024-09-04 at 14 01 54](https://github.com/user-attachments/assets/a6cec658-46e2-4eba-a096-f000473fe101)

But the submitted data seems to be ok (no whitespaces at the front or end of the string):
![Screenshot 2024-09-04 at 14 09 57](https://github.com/user-attachments/assets/6946b695-654a-4185-a445-1cb71e3ba608)

am I missing something?

**Comment by zepich** [comment]
Hi @fbentele 

Thank you very much for your issue!

Can you list all special characters used in this or other invalid messages? Did the user maybe use some emojis or something else that breaks because of the encoding?

The text field is not a WYSIWYG field, correct?

Kind regards,

zepich

**Comment by fbentele** [comment]
Hey @zepich 
That was just a wild guess. Actually it's not a WYSIWYG field, only a textarea, my second guess would be the length of the string (its 480-something chars long). And it has a line-break `\n` in it, maybe this is the problem?
No emojis but:
- è
- é
- ô
- ç
any hints are much appreciated.
regards, flo

**Comment by zepich** [comment]
Wait, do you see the line break in mosparo as `\n` (as text)?

You should see the message with real line breaks not with `\n` visible...
![image](https://github.com/user-attachments/assets/63ce9f32-df43-4cad-9f10-911e1421d57d)

**Comment by fbentele** [comment]
yes I can approve that I don't actually see the \n 
I just assumed that it's a line break like `\n` in mosparo it is printed on a new line.
![Screenshot 2024-09-04 at 15 29 56](https://github.com/user-attachments/assets/ab122edd-66e2-4c31-88ae-f351c5d91fe2)

**Comment by zepich** [comment]
Hi @fbentele 

Okay, thank you very much for your response. That's a tricky problem... 

Did the user use `'` or `"` in the message?

Kind regards,

zepich

**Comment by fbentele** [comment]
Indeed! The response contains three `'` chars, but no `"`. they are displayed correctly in mosparo.

**Comment by zepich** [comment]
Hi @fbentele 

Okay. Can you look at how these characters look in the `$_POST` variable in PHP if you test submitting the form with such a character in it? Are they maybe escaped with a `\`?

Kind regards,

zepich

**Comment by fbentele** [comment]
Hey @zepich 
yes, they are being escaped with a `\ ` 
I think this is the default behaviour of a regular form post to php. When i run something like
```
var_dump($_POST)
// or
print_r($_POST)
```

i can see the char is being escaped like: `\'`.

**Comment by zepich** [comment]
Hi @fbentele 

Okay, perfect. And if you submit the form with content with `'`, do you also have the issue with the validation in mosparo?

If so, can you remove the backslashes before sending the data to mosparo?

Kind regards,

zepich

**Comment by fbentele** [comment]
Yep, that's it! If i remove the slashes

```
	$_POST['description'] = stripslashes($_POST['description']);
```
I can successfully submit the same form without errors.

Now the question is: is this a bug or a feature ;-)

I would love to not stripslash all the post-fields in a form post. What's your take?

**Comment by zepich** [comment]
Hi @fbentele 

Perfect. Thank you very much for your feedback. I'm happy that we found the issue.

> Now the question is: is this a bug or a feature ;-)

The answer to this question is: it's a feature of WordPress. The function is called `wp_magic_quotes()` in `wp-settings.php`. Before this step, the `$_POST` value does not have any `\`, after this function, it has the `\`.

I guess it's to prevent SQL injections by simply escaping everything.

I've tested the mosparo WordPress Integration with this character, and all form plugins handle it correctly (I guess they strip the slashes again before mosparo receives the form data), so I do not see this as a bug of mosparo. It's something we have to add to the documentation.

Where do you see the problem of stripping the slashes of the form data you send to mosparo?

I do not see a problem if you strip the slashes only for the data you send to mosparo. Something like

```php
$formData = $_POST;
$formData['description'] = stripslashes($formData['description']);
$result = $client->verifySubmission( $formData, $mosparo_submit_token, $mosparo_validation_token );
unset($formData);
```

And everywhere else, you continue working with the `$_POST` variable. With this, you strip the slashes only for the values you send to mosparo, and the mosparo API client does not store the information in a WordPress database, so there is no risk from my perspective. Or do you see a risk with that approach?

Technically, it would be possible to strip the slashes within the API client, but the problem there is that we do not know where you use the library. There may be a case when you expect the slashes in which we would also break the validation by removing the required slashes. Let's say you want to post a message in this issue with an example like `\'` in the text, but then the API client would remove that slash. mosparo then would not validate correctly, and we have the same problem, but from the other side around.

What do you think?

### One additional thing

I don't know if you provided your full validation code or if it's just a short example. However, I would like to highlight that the bypass validation is missing in your code example. If that's the actual code, an attacker could change the field type of a field to `password`, for example, before starting the mosparo validation. Since mosparo does not validate the `password` fields, spam will not be detected. After mosparo validated the fields, the attacker could change the field type back to `text` and submit the form with spam.

For that, you should verify that all fields were verified by mosparo during the verification process.

You can read more about that here: https://documentation.mosparo.io/docs/integration/bypass_protection
If you have any questions regarding that, please let me know.

Please let me know if you have any other questions.

Kind regards,

zepich

**Comment by fbentele** [comment]
Hi @zepich 
You are awesome! 🥳  Thanks for your summary. I am totally with you. I can (and should) handle the stripslash thing on my side. I was not aware of this wordpress feature until today... I am also with you concerning the api client, it should not touch the user input. I will handle it on my side. Maybe you can just add a hint to the docs page?

Regarding the form validation: i use a seperate logic to handle form validation in the backend, so i do not rely on the validation part of mosparo. If a request gets to this point, it is already validated. Thanks for the hint anyway!

I'd love to contribute in any way to this awesome project. As a tester, or any other way.

Regards,
Flo

**Comment by zepich** [comment]
Hi @fbentele 

Thank you very much for your kind words and feedback! It gives me the energy to continue working on this project!

I'm happy that we were able to find the problem and solution for your problem.

We would love to hear your ideas if you have any ideas or suggestions for enhancing mosparo. As soon as we have a new beta version ready (sometime in October/November, I think), we're looking forward to your testing feedback (if you have time).

I wish you a lovely evening.

Kind regards,

zepich
