### ISSUE TITLE
Missing Content-Security-Policy header

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#45]
Hi,
i noticed that Mosparo currently does not set Content-Security-Policy (CSP) headers, which are important security headers.

Therefore I have created a first draft with which these are set via the ".htaccess" file, but in my draft "script-src" and "style-src" are set with "unsafe-inline".

Pull request: https://github.com/mosparo/mosparo/pull/44

**Comment by zepich** [comment]
Hi @Digi92 

Thank you very much for bringing this issue to our attention.

I will try to add a fix without using the unsafe-inline. It should be possible, but I have to make some adjustments.

We will reply as soon as we've fixed this issue.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @Digi92

Thank you again for your issue and the pull request.

We've investigated the issue and added the headers you added in your pull request. We're using a Symfony module to provide these headers. We can hash our inline JavaScript codes with the module and ensure we do not need the `unsafe-inline` flags. By default, only the `default-src` option is set since mosparo is using resources from the mosparo host itself.

If a page has an inline script, the bundle automatically adds the hash in the `script-src` option. 

I've removed possible inline styles, URLs starting with `data:`, and other things that cannot work with the CSP headers. There is one exception: on the design settings page, we cannot provide a clean CSP header. The color picker uses inline styles and `data:` URLs. Therefore, we must now use the `unsafe-inline` option on this page. We will fix that with the next major version (v0.4) since we're planning a refactoring of the design settings page anyways (see #46).

I hope this solution fits your expectations too. I will close your pull request without merging (because changing the .htaccess file would only work for Apache servers, not for nginx).

The new version, v0.3.15, with the security headers and other fixes, will be released tomorrow.

Thank you very much for making mosparo better!

Kind regards,

zepich
