### ISSUE TITLE
Missing attribute "autocomplete"  on password field

### ISSUE THREAD

**Issue by Digi92** [mosparo/mosparo#59]
Hi,
we have run a small security test against the Mosparo backend.
The only result was that no "autocomplete='off'" is set for password fields.

For this reason I have created a pull request that contains the attribute on the password fields: [58](https://github.com/mosparo/mosparo/pull/58)

**Comment by zepich** [comment]
Hi @Digi92

Thank you very much for your issue, pull request, and your feedback in general.

We've merged the pull request and added a fix for an additional password field in the setup so that all password fields now have the `autocomplete` attribute set to `off` or `new-password` (`PasswordFormType`).

We've released these fixes as [v0.3.18](https://github.com/mosparo/mosparo/releases/tag/v0.3.18).

Thank you also for doing the security test. If you have any other issues or recommendations, we're always happy to hear them. You do not have to send us a pull request for security topics. We're always happy when we can enhance the security of mosparo.

Thank you very much for your work, and have a nice evening.

Kind regards,

zepich
