### ISSUE TITLE
Error 500 on check version

### ISSUE THREAD

**Issue by Silbad** [mosparo/mosparo#65]
Hi,
Occasionally I get a timeout when we check the version:
`[2023-05-25T18:45:36.326678+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpClient\Exception\TransportException: "fopen(https://104.238.666.666/stable.json): Failed to open stream: Connection timed out"`
And when I try to update : 
`[2023-05-25T18:49:52.884020+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Failed to create "/var/www/mosparo.mysite.com/public/update-log": mkdir(): Permission denied"`
Another write permission ? on public ?
Thanks

**Comment by zepich** [comment]
Hi @Silbad 

Sorry for the issues! :(

1. Yes, there is a network issue with one of our providers. I hoped it would only last some minutes, but it is now a bit long. I will adjust the DNS settings.

2. Yes, sorry, I forgot to add that to the list of required write access paths:
```
mkdir public/update-log
chown -R www-data public/update-log
```
In this directory, mosparo will write the update log since the PHP process is unavailable while mosparo gets updated.

I will adjust the list of required write access locations with the next version and create an empty directory in the package.

Kind regards,

zepich

**Comment by zepich** [comment]
I'm sorry, I didn't think about that before. 

Of course, the owner of all files of mosparo must be set to www-data user (or to the user running the PHP process) to be able to use the update functionality in the web interface. Otherwise, the files could not be updated.

If you do not want that (owner of all files to www-data), you could also use the update command via the CLI: https://documentation.mosparo.io/docs/installation/update#installing-the-update-from-the-command-line

**Comment by Silbad** [comment]
``php bin/console mosparo:self-update`
With the command line, same pb, damned ^^
` Your user is not the owner of these files or is the root user. You should execute the command as owner of the files.`

**Comment by zepich** [comment]
Have you tried the command with the root user (or with sudo)? If yes, you can continue the update since it's just a question. After the update, please recheck the write access for the www-data user for all three paths (config/env.mosparo.php, public/resources, var/). They should not be changed, but you should verify that so that no other problems occur.

Otherwise, you could execute the command as the owner of the files like this:

```
sudo -u [username] php bin console mosparo:self-update
```
(replace [username] with the name of the user)

But before you do that, you would have to change the owner of the var/ directory back to the original user and change it after the update again to www-data (the other paths (config/env.mosparo.php and public/resources) are not affected by the update).

**Comment by Silbad** [comment]
I try with root, but i have another error : 
`20:18:18 CRITICAL  [console] Error thrown while running command "mosparo:self-update". Message: "Class "ZipArchive" not found" ["exception" => Error { …},"command" => "mosparo:self-update","message" => "Class "ZipArchive" not found"]`

**Comment by zepich** [comment]
The `zip` extension is not available/loaded. Have you installed this extension? I guess you have because otherwise, the setup would not work. It may not be loaded on the CLI PHP config.

Please check with the following command for the module:
```
php -m
```

**Comment by Silbad** [comment]
Mm it's installed but not loaded, which explains that

**Comment by Silbad** [comment]
Strange, I've re-installed it and it still won't load... I'll try tomorrow. Thanks.

**Comment by zepich** [comment]
Good Morning @Silbad 

Have you installed two versions of PHP on your server? For example, php8.1 and php8.2?

Maybe you're using php8.1 with the command `php`, where the extension is not installed?

Please check with `php -v` if you use the correct version. If it shows the wrong version, try the update command with `php8.2` instead of `php`.

Kind regards,

zepich

**Comment by Silbad** [comment]
Hello that's it !
`php8.2 bin/console mosparo:self-update`
Tks
